title: "Kylo Parisher Portfolio"
description: "Personal portfolio of Kylo Parisher (KP) focusing on cybersecurity, AI/ML, PR-CYBR, the G8 System, ESI teaching, space & quantum explorations, and psionics."
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jemoji
show_downloads: false
github_username: cywf
