title: "Kylo Parisher Portfolio Dashboard"
description: "Live dashboard visualizing operational health and performance of open-source projects including PR-CYBR, F4ORGE, and AI-agent initiatives"
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jemoji
show_downloads: false
github_username: cywf

# Include HTML files
include:
  - assets

# Exclude backup files
exclude:
  - index.md.bak
